version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefikダッシュボード用
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/conf:/etc/traefik
      - ./traefik/certs:/etc/certs
    restart: unless-stopped

  web:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      # 本番環境用設定
      - "traefik.http.routers.web-prod.rule=Host(`banananbo.com`)"
      - "traefik.http.routers.web-prod.entrypoints=web"
      # 開発環境用設定
      - "traefik.http.routers.web-dev.rule=Host(`lvh.me`)"
      - "traefik.http.routers.web-dev.entrypoints=web"
      # 共通設定
      - "traefik.http.services.web.loadbalancer.server.port=80"
    volumes:
      - ./web/html:/usr/share/nginx/html
    restart: unless-stopped 