server:
  port: 8081

spring:
  application:
    name: api-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:user_db}
    username: ${MYSQL_USER:appuser}
    password: ${MYSQL_PASSWORD:apppassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 1
      initialization-fail-timeout: 60000
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
    clean-disabled: false
    clean-on-validation-error: true
    repair-on-migrate: true
    connect-retries: 10
    connect-retries-interval: 5

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
  issuerUri: ${AUTH0_ISSUER_URI}
  redirectUri: ${AUTH0_REDIRECT_URI}
  logoutRedirectUri: ${AUTH0_LOGOUT_REDIRECT_URI}

openai:
  api:
    key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}

app:
  job:
    batch-size: 10
    max-retries: 3
    interval: 180000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 